// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

// Program mdai-data-filtration-collector is an OpenTelemetry Collector binary.
package main

import (
	"log"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/confmap"
	mdaiprovider "github.com/mydecisive/mdaiprovider"
	envprovider "go.opentelemetry.io/collector/confmap/provider/envprovider"
	fileprovider "go.opentelemetry.io/collector/confmap/provider/fileprovider"
	"go.opentelemetry.io/collector/otelcol"
)

func main() {
	info := component.BuildInfo{
		Command:     "mdai-data-filtration-collector",
		Description: "MyDecisive Data Filtration Collector",
		Version:     "",
	}

	set := otelcol.CollectorSettings{
		BuildInfo: info,
		Factories: components,
		ConfigProviderSettings: otelcol.ConfigProviderSettings{
			ResolverSettings: confmap.ResolverSettings{
				ProviderFactories: []confmap.ProviderFactory{
					mdaiprovider.NewFactory(),
					envprovider.NewFactory(),
					fileprovider.NewFactory(),
				},
			},
		},
		ProviderModules: map[string]string{
			mdaiprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme(): "github.com/mydecisive/mdaiprovider v0.2.0",
			envprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme(): "go.opentelemetry.io/collector/confmap/provider/envprovider v1.48.0",
			fileprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme(): "go.opentelemetry.io/collector/confmap/provider/fileprovider v1.48.0",
    	},
		ConverterModules: []string{
		},
	}

	if err := run(set); err != nil {
		log.Fatal(err)
	}
}

func runInteractive(params otelcol.CollectorSettings) error {
	cmd := otelcol.NewCommand(params)
	if err := cmd.Execute(); err != nil {
		log.Fatalf("collector server run finished with error: %v", err)
	}

	return nil
}
