// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("attributeextractor")
	ScopeName = "github.com/decisiveai/mdai-collectors/attributeextractorconnector"
)

const (
	TracesToMetricsStability  = component.StabilityLevelDevelopment
	MetricsToMetricsStability = component.StabilityLevelDevelopment
	LogsToMetricsStability    = component.StabilityLevelDevelopment
)
